#!/usr/bin/env pwsh
# DoingTeam - MrDoing CLI installer
# Generated by https://www.doingteam.com/install.ps1
#
# Usage: irm https://www.doingteam.com/install.ps1 | iex

$ErrorActionPreference = "Stop"

function Write-Step { param([string]$m) Write-Host ""; Write-Host ">> $m" -ForegroundColor Cyan }
function Write-Ok   { param([string]$m) Write-Host "   OK: $m" -ForegroundColor Green }
function Write-Warn { param([string]$m) Write-Host "   WARN: $m" -ForegroundColor Yellow }
function Write-Err  { param([string]$m) Write-Host "   ERR: $m" -ForegroundColor Red }

Write-Host ""
Write-Host "== MrDoing CLI installer ==" -ForegroundColor Magenta

# --- install dir ---
$InstallDir = "$env:LOCALAPPDATA\MrDoing"
$BinPath    = Join-Path $InstallDir "mrdoing.exe"
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
}

# --- download ---
Write-Step "Downloading the latest Windows build"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
try {
    Invoke-WebRequest -Uri "https://www.doingteam.com/download/cli?os=windows" -OutFile $BinPath -UseBasicParsing
} catch {
    Write-Err "Download failed: $_"
    Write-Err "The DoingTeam admin may not have uploaded a Windows release yet."
    exit 1
}
Write-Ok "Saved: $BinPath"

# --- add install dir to User PATH ---
# Putting the dir on PATH makes 'mrdoing' resolvable in CMD, git bash,
# VS Code terminals, etc. -- not just PowerShell. The PowerShell
# function below is kept for zero-latency launching in PS sessions.
Write-Step "Adding install dir to User PATH"
$userPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if (-not $userPath) { $userPath = "" }
$pathParts = $userPath -split ";" | Where-Object { $_ -and ($_ -ne $InstallDir) }
$pathParts = ,$InstallDir + $pathParts
$newUserPath = ($pathParts -join ";")
[Environment]::SetEnvironmentVariable("PATH", $newUserPath, "User")
$env:PATH = "$InstallDir;$env:PATH"
Write-Ok "User PATH now includes: $InstallDir"

# --- register mrdoing function ---
Write-Step "Registering 'mrdoing' command"

[Environment]::SetEnvironmentVariable("MRDOING_HOME", $InstallDir, "User")
$env:MRDOING_HOME = $InstallDir

if (-not (Test-Path $PROFILE)) {
    New-Item -ItemType File -Force -Path $PROFILE | Out-Null
}

$mark_begin = "# >>> mrdoing"
$mark_end   = "# <<< mrdoing"
$profileText = Get-Content -Raw $PROFILE -ErrorAction SilentlyContinue
if (-not $profileText) { $profileText = "" }

if ($profileText -match [regex]::Escape($mark_begin)) {
    $pattern = [regex]::Escape($mark_begin) + ".*?" + [regex]::Escape($mark_end)
    $profileText = [regex]::Replace($profileText, $pattern, "", "Singleline").TrimEnd()
}

$exePath = $BinPath.Replace("\", "\\")
$block = @"

$mark_begin
# Added by DoingTeam installer - delete this block to uninstall.
function mrdoing { & "$exePath" @args }
$mark_end

"@

$newProfile = $profileText.TrimEnd() + "`r`n" + $block
Set-Content -Path $PROFILE -Value $newProfile -Encoding UTF8
Write-Ok "Added 'mrdoing' function to $PROFILE"

# --- verify ---
Write-Step "Verifying"
try {
    $versionOutput = & $BinPath --version 2>&1 | Select-Object -First 1
    Write-Ok "mrdoing --version: $versionOutput"
} catch {
    Write-Warn "Could not run mrdoing. Try: $BinPath"
}

Write-Host ""
Write-Host "======================================" -ForegroundColor Magenta
Write-Host "  MrDoing installed."                   -ForegroundColor Magenta
Write-Host "======================================" -ForegroundColor Magenta
Write-Host ""
Write-Host "  Open a NEW terminal (PowerShell, CMD, git bash,"  -ForegroundColor DarkGray
Write-Host "  or VS Code) and type:"                             -ForegroundColor DarkGray
Write-Host ""
Write-Host "      mrdoing"                                       -ForegroundColor White
Write-Host ""
Write-Host "  from any project directory."                       -ForegroundColor DarkGray
Write-Host ""
